// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwAwKR1mmPw40AXwdSSB0uFiSQXLTIU24',
    appId: '1:751477111837:web:6c7ce837db2043767c1af4',
    messagingSenderId: '751477111837',
    projectId: 'douae-e94ec',
    authDomain: 'douae-e94ec.firebaseapp.com',
    storageBucket: 'douae-e94ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ybXvNQbAnpaPLjqlA9IA2Gnod5Ik0KA',
    appId: '1:751477111837:android:06a95044cf3aaa207c1af4',
    messagingSenderId: '751477111837',
    projectId: 'douae-e94ec',
    storageBucket: 'douae-e94ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACL0POAoI4HlUfGRVAbXT6jWJSeNO4alg',
    appId: '1:751477111837:ios:b47f1ebf910791347c1af4',
    messagingSenderId: '751477111837',
    projectId: 'douae-e94ec',
    storageBucket: 'douae-e94ec.firebasestorage.app',
    iosBundleId: 'com.example.berifApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACL0POAoI4HlUfGRVAbXT6jWJSeNO4alg',
    appId: '1:751477111837:ios:b47f1ebf910791347c1af4',
    messagingSenderId: '751477111837',
    projectId: 'douae-e94ec',
    storageBucket: 'douae-e94ec.firebasestorage.app',
    iosBundleId: 'com.example.berifApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBYdbovtDQhSdt-aJw5gVTRq2HrbHPKb0',
    appId: '1:751477111837:web:d750b45afd5338257c1af4',
    messagingSenderId: '751477111837',
    projectId: 'douae-e94ec',
    authDomain: 'douae-e94ec.firebaseapp.com',
    storageBucket: 'douae-e94ec.firebasestorage.app',
  );

}